workflows:
    quote_flow:
        transition_definitions:
            quote_creating_definition:
                preconditions:
                   '@and':
                       - '@neq':  [$status.id, 'lost']
                       - '@neq':  [$status.id, 'won']
                       - '@type': [$customer.getTarget, 'Oro\Bundle\CustomerBundle\Entity\Customer']
                actions:
                       - '@redirect':
                          route: 'oro_sales_opportunity_view'
                          route_parameters:
                              id: $opportunity.id

