system_configuration:
    groups:
        account_settings:
            title: oro.customer_account_bridge.system_configuration.groups.account_settings.title
            icon: 'icon-book'
        customer_account_settings:
            title: oro.customer_account_bridge.system_configuration.groups.customer_account_settings.title

    fields:
        oro_customer_account_bridge.customer_account_settings:
            data_type: string
            type: oro_config_customer_account_choice
            options:
                label: oro.customer_account_bridge.system_configuration.fields.strategy_creating_customers_account.label
                tooltip: oro.customer_account_bridge.system_configuration.fields.strategy_creating_customers_account.tooltip
                choices:
                    each: oro.customer_account_bridge.system_configuration.fields.strategy_creating_customers_account.choices.each
                    root: oro.customer_account_bridge.system_configuration.fields.strategy_creating_customers_account.choices.root
                constraints:
                    - NotBlank: ~

        oro_customer_account_bridge.commerce_customers_section_name:
            data_type: string
            type: text
            priority: 60
            options:
                label: oro.customer_account_bridge.system_configuration.fields.commerce_customers_section_name.label
                constraints:
                    - NotBlank: ~
                    - Type: string

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            account_settings:
                                children:
                                    customer_account_settings:
                                        children:
                                            - oro_customer_account_bridge.commerce_customers_section_name
                                            - oro_customer_account_bridge.customer_account_settings
